In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor,GradientBoostingRegressor
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from keras.models import Sequential, Model
from keras.layers import Dense, LSTM, Conv2D, Dropout, MaxPool2D, Flatten
from sklearn.metrics import mean_absolute_error
from xgboost import XGBRegressor
from sklearn.feature_selection import SelectFromModel
from sklearn.metrics import accuracy_score, r2_score
import numpy as np

Using TensorFlow backend.

In [ ]:
from sklearn.metrics import mean_absolute_error

x_pred = selection_model.predict(select_x_test)
mae = mean_absolute_error(y_test, x_pred)
print('mae는',mae)

In [2]:
train = pd.read_csv('train.csv', index_col=0)
test = pd.read_csv('test.csv', index_col=0)
submission = pd.read_csv('sample_submission.csv', index_col=0)

In [3]:
x = train.iloc[:,:71]
y = train.iloc[:,71:]

In [6]:
x = x.interpolate()
test = test.interpolate()

In [7]:
x = x.fillna(x.mean())
test = test.fillna(test.mean())

In [14]:
y

        hhb  hbo2     ca    na
id
0      5.59  4.32   8.92  4.29
1      0.00  2.83   7.25  4.64
2     10.64  3.00   8.40  5.16
3      5.67  4.01   5.05  4.35
4     11.97  4.41  10.78  2.42
...     ...   ...    ...   ...
9995  12.68  4.11  12.31  0.10
9996   8.46  4.11  10.46  3.12
9997   9.84  3.20  10.45  2.06
9998   6.38  4.06  11.28  4.03
9999   9.35  4.34   9.73  3.54

[10000 rows x 4 columns]

In [15]:
y1 = y.iloc[:,0]
y2 = y.iloc[:,1]
y3 = y.iloc[:,2]
y4 = y.iloc[:,3]

In [9]:
x.shape

(10000, 71)

In [9]:
# 전처리
from sklearn.preprocessing import RobustScaler, StandardScaler
scaler = RobustScaler()
scaler.fit(x) 
x = scaler.transform(x)
test = scaler.transform(test)

# from sklearn.decomposition import PCA
# pca = PCA(n_components=12)
# pca.fit(x)
# x = pca.transform(x)
# x_predict = pca.transform(x_predict)

train = np.array(train)
x_predict = np.array(test)

In [167]:
# from sklearn.preprocessing import MinMaxScaler
# scaler = MinMaxScaler()
# scaler.fit(x) 
# x = scaler.transform(x)
# x_predict = scaler.transform(x_predict)

In [14]:
# 두번째꺼 0.71
x_train, x_test, y_train, y_test = train_test_split(x,y2, test_size=0.2, random_state=43)
model = RandomForestRegressor(n_estimators=300)
model.fit(x_train,y_train)
y_pred = model.predict(x_test) # 회귀던 분류던 사용할 수 있음
mae = mean_absolute_error(y_pred, y_test)
print('랜덤포레스트 mae 는', mae)

thresholds = np.sort(model.feature_importances_)

for thresh in thresholds : # 컬럼수만큼 돈다! 빙글빙글
    selection = SelectFromModel(model, threshold=thresh, prefit=True)
    selection_x_train = selection.transform(x_train)
    # print(selection_x_train.shape) # 칼럼이 하나씩 줄고 있는걸 알 수 있음 (가장 중요 x를 하나씩 지우고 있음)
    
    selection_model = XGBRegressor()
    selection_model.fit(selection_x_train, y_train)

    select_x_test = selection.transform(x_test)
    x_pred = selection_model.predict(select_x_test)

    mae = mean_absolute_error(y_test, x_pred)
    print('mae는',mae)

    modelpath = './model/xgb_save/auc' + str(mae) + '.dat'

C:\Users\bitcamp\anaconda3\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.

랜덤포레스트 mae 는 0.7082098
mae는 0.7349076338338851
mae는 0.7501098101425171
mae는 0.7350139020013808
mae는 0.7308949107527732
mae는 0.741435033583641
mae는 0.7397070063066483
mae는 0.7306379121851921
mae는 0.736061611981392
mae는 0.7321029380917549
mae는 0.7333246780228615
mae는 0.7379412888479233
mae는 0.7338554907870294
mae는 0.7391021495962143
mae는 0.736312471203804
mae는 0.7382736615347862
mae는 0.7358255023241043
mae는 0.7426149238824844
mae는 0.7380071192646026
mae는 0.7390459563469888
mae는 0.7333999435138703
mae는 0.7443771235227585
mae는 0.7237133423662185
mae는 0.7412446620965004
mae는 0.7329548334932326
mae는 0.7356858549809456
mae는 0.7341450897717475
mae는 0.7318013655757905
mae는 0.7370261344099045
mae는 0.7329287794709205
mae는 0.7406329316210747
mae는 0.7378262117576598
mae는 0.7271239749360083
mae는 0.7184309677505493
mae는 0.7401643600440024
mae는 0.7272806949710846
mae는 0.7537565509343147
mae는 0.7479528230524063
mae는 0.7704446580839158
mae는 0.7655433742046356
mae는 0.7648859864664077
mae는 0.7639058007335664
mae는 0.7465942953896522
mae는 0.7525982703137398
mae는 0.7634324163413048
mae는 0.7658290528821945
mae는 0.7596875281381607
mae는 0.7701924499893189
mae는 0.7647936013007164
mae는 0.7728226742959022
mae는 0.7669160694551467
mae는 0.767794878358841
mae는 0.7683046424436568
mae는 0.7649207567095757
mae는 0.7642119248914718
mae는 0.7763056101751328
mae는 0.7691099311876296
mae는 0.7665784274816513
mae는 0.7742649702739716
mae는 0.7837896693563461
mae는 0.7683978143835067
mae는 0.7654061342859267
mae는 0.771379654481411
mae는 0.7739242677593231
mae는 0.7768927342677115
mae는 0.7882615752744675
mae는 0.7776755734062194
mae는 0.7729919307732582
mae는 0.7840039873433113
mae는 0.7917958050394057
mae는 0.7981828317165375
mae는 0.8052504149675369

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y1, test_size=0.2, random_state=43)
model = RandomForestRegressor(n_estimators=300)
model.fit(x_train,y_train)
y_pred = model.predict(x_test) # 회귀던 분류던 사용할 수 있음
mae = mean_absolute_error(y_pred, y_test)
print('랜덤포레스트 mae 는', mae)

for thresh in thresholds : # 컬럼수만큼 돈다! 빙글빙글
    selection = SelectFromModel(model, threshold=thresh, prefit=True)
    selection_x_train = selection.transform(x_train)
    # print(selection_x_train.shape) # 칼럼이 하나씩 줄고 있는걸 알 수 있음 (가장 중요 x를 하나씩 지우고 있음)
    
    selection_model = XGBRegressor()
    selection_model.fit(selection_x_train, y_train)

    select_x_test = selection.transform(x_test)
    x_pred = selection_model.predict(select_x_test)

    mae = mean_absolute_error(y_test, x_pred)
    print('mae는',mae)

#     modelpath = './model/xgb_save/auc' + str(mae) + '.dat'

C:\Users\bitcamp\anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until

In [13]:
print(x.shape)
print(y1.shape)
print(y2.shape)
print(y3.shape)
print(y4.shape)

(10000, 71)
(10000, 0)
(10000, 0)
(10000, 0)
(10000, 0)

In [16]:
x_train, x_test, y_train, y_test = train_test_split(x,y1, test_size=0.2, random_state=43)
model = RandomForestRegressor(n_estimators=300)
model.fit(x_train,y_train)
y_pred = model.predict(x_test) # 회귀던 분류던 사용할 수 있음
mae = mean_absolute_error(y_pred, y_test)
print('랜덤포레스트 mae 는', mae)

x_train, x_test, y_train, y_test = train_test_split(x,y2, test_size=0.2, random_state=43)
model = RandomForestRegressor(n_estimators=300)
model.fit(x_train,y_train)
y_pred = model.predict(x_test) # 회귀던 분류던 사용할 수 있음
mae = mean_absolute_error(y_pred, y_test)
print('랜덤포레스트 mae 는', mae)

x_train, x_test, y_train, y_test = train_test_split(x,y3, test_size=0.2, random_state=43)
model = RandomForestRegressor(n_estimators=300)
model.fit(x_train,y_train)
y_pred = model.predict(x_test) # 회귀던 분류던 사용할 수 있음
mae = mean_absolute_error(y_pred, y_test)
print('랜덤포레스트 mae 는', mae)

x_train, x_test, y_train, y_test = train_test_split(x,y4, test_size=0.2, random_state=43)
model = RandomForestRegressor(n_estimators=300)
model.fit(x_train,y_train)
y_pred = model.predict(x_test) # 회귀던 분류던 사용할 수 있음
mae = mean_absolute_error(y_pred, y_test)
print('랜덤포레스트 mae 는', mae)

랜덤포레스트 mae 는 1.28386345
랜덤포레스트 mae 는 0.7095984333333333
랜덤포레스트 mae 는 2.1874671833333332
랜덤포레스트 mae 는 1.4084883333333331

# GradientBoostingRegressor

In [17]:
x_train, x_test, y_train, y_test = train_test_split(x,y1, test_size=0.2, random_state=43)

model = GradientBoostingRegressor(n_estimators=300)
model.fit(x_train,y_train)
y_pred = model.predict(x_test) # 회귀던 분류던 사용할 수 있음
mae = mean_absolute_error(y_pred, y_test)
print('GradientBoostingRegressor mae 는', mae)

x_train, x_test, y_train, y_test = train_test_split(x,y2, test_size=0.2, random_state=43)
model = GradientBoostingRegressor(n_estimators=300)
model.fit(x_train,y_train)
y_pred = model.predict(x_test) # 회귀던 분류던 사용할 수 있음
mae = mean_absolute_error(y_pred, y_test)
print('GradientBoostingRegressor mae 는', mae)

x_train, x_test, y_train, y_test = train_test_split(x,y3, test_size=0.2, random_state=43)
model = GradientBoostingRegressor(n_estimators=300)
model.fit(x_train,y_train)
y_pred = model.predict(x_test) # 회귀던 분류던 사용할 수 있음
mae = mean_absolute_error(y_pred, y_test)
print('GradientBoostingRegressor mae 는', mae)

x_train, x_test, y_train, y_test = train_test_split(x,y4, test_size=0.2, random_state=43)
model = GradientBoostingRegressor(n_estimators=300)
model.fit(x_train,y_train)
y_pred = model.predict(x_test) # 회귀던 분류던 사용할 수 있음
mae = mean_absolute_error(y_pred, y_test)
print('GradientBoostingRegressor mae 는', mae)

GradientBoostingRegressor mae 는 1.4974700975648207
GradientBoostingRegressor mae 는 0.7325261688602795
GradientBoostingRegressor mae 는 2.262903047825188
GradientBoostingRegressor mae 는 1.4216185025697796

In [18]:
x_train, x_test, y_train, y_test = train_test_split(x,y1, test_size=0.2, random_state=43)

model = GradientBoostingRegressor()
model.fit(x_train,y_train)
y_pred = model.predict(x_test) # 회귀던 분류던 사용할 수 있음
mae = mean_absolute_error(y_pred, y_test)
print('GradientBoostingRegressor mae 는', mae)

x_train, x_test, y_train, y_test = train_test_split(x,y2, test_size=0.2, random_state=43)
model = GradientBoostingRegressor()
model.fit(x_train,y_train)
y_pred = model.predict(x_test) # 회귀던 분류던 사용할 수 있음
mae = mean_absolute_error(y_pred, y_test)
print('GradientBoostingRegressor mae 는', mae)

x_train, x_test, y_train, y_test = train_test_split(x,y3, test_size=0.2, random_state=43)
model = GradientBoostingRegressor()
model.fit(x_train,y_train)
y_pred = model.predict(x_test) # 회귀던 분류던 사용할 수 있음
mae = mean_absolute_error(y_pred, y_test)
print('GradientBoostingRegressor mae 는', mae)

x_train, x_test, y_train, y_test = train_test_split(x,y4, test_size=0.2, random_state=43)
model = GradientBoostingRegressor()
model.fit(x_train,y_train)
y_pred = model.predict(x_test) # 회귀던 분류던 사용할 수 있음
mae = mean_absolute_error(y_pred, y_test)
print('GradientBoostingRegressor mae 는', mae)

GradientBoostingRegressor mae 는 1.5836630766001003
GradientBoostingRegressor mae 는 0.7353891915358228
GradientBoostingRegressor mae 는 2.308202350435541
GradientBoostingRegressor mae 는 1.4270150009757576

# XGBRegressor()

In [21]:
x

array([[ 5.00000000e-01,  1.53168849e+00,  1.36606433e+00, ...,
        -5.30995738e-04, -1.95528048e-03, -3.69928276e-03],
       [-1.00000000e+00, -2.43334892e-01, -2.41556281e-01, ...,
        -5.31572788e-04,  1.95632418e+03, -3.69877614e-03],
       [ 5.00000000e-01, -2.43334892e-01, -1.18571976e-01, ...,
        -5.32149838e-04, -1.95622121e-03, -3.69826951e-03],
       ...,
       [-1.00000000e+00,  2.45025725e+00,  2.11328092e+00, ...,
         6.59217115e+00,  3.03019857e+01,  3.06502750e+01],
       [-5.00000000e-01,  4.50301684e+00,  3.55394352e+00, ...,
         9.88799895e+00,  5.65968447e-01,  1.07490026e+00],
       [-1.00000000e+00,  9.00350795e-01,  8.12242342e-01, ...,
         1.31838267e+01,  6.54725387e-01,  2.92896432e+00]])

In [23]:
x = pd.DataFrame(x)

In [24]:
y1 = pd.DataFrame(y1)

In [25]:
y2 = pd.DataFrame(y2)

In [35]:
x = x.reset_index()

,index,0,1,2,3,4,5,6,7,8,...,61,62,63,64,65,66,67,68,69,70
0,0,0.5,1.531688,1.366064,1.348957,1.179703,1.129366,1.031533,0.973250,0.963339,...,21.325753,-0.000738,25.008361,-0.001391,24.594814,-0.000336,70.288663,-0.000531,-0.001955,-0.003699
1,1,-1.0,-0.243335,-0.241556,-0.184363,-0.236173,-0.241899,-0.219267,-0.265968,-0.294603,...,714.348788,-0.000738,1994.444211,3548.779977,4456.664085,5601.841811,5999.294212,-0.000532,1956.324177,-0.003699
2,2,0.5,-0.243335,-0.118572,-0.165968,-0.146762,-0.123755,-0.099449,-0.048321,-0.044985,...,-0.001150,-0.000738,-0.000723,-0.001391,-0.000887,-0.000336,-0.000296,-0.000532,-0.001956,-0.003698
3,3,-1.0,1.043054,0.928122,0.763915,0.780322,0.700080,0.645123,0.687316,0.693794,...,34.395894,17.256368,0.002207,46.704813,74.523893,119.090616,219.146549,0.071375,82.378970,-0.003698
4,4,-0.5,4.505075,3.530311,2.778283,2.212718,1.815929,1.476635,1.217777,1.025065,...,-0.001152,8.627815,0.005136,0.012634,0.047489,0.080026,109.573127,0.143282,41.188508,-0.003697
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9995,-0.5,0.875889,0.890131,0.978402,1.026985,1.053623,1.063049,1.020015,0.993813,...,-0.001152,-0.000086,0.000303,1.850411,-0.000662,-0.000336,0.001258,0.000516,-0.001676,0.000478
9996,9996,0.0,-0.122521,-0.206183,-0.128323,-0.201994,-0.159140,-0.178613,-0.222224,-0.223633,...,-0.001097,0.029309,-0.000717,-0.001372,-0.000827,-0.000234,-0.000089,3.296343,-0.001839,-0.003379
9997,9997,-1.0,2.450257,2.113281,1.913165,1.677090,1.484911,1.326271,1.183276,1.034686,...,18.610317,0.058704,0.007610,18.170452,16.020466,28.504445,22.861835,6.592171,30.301986,30.650275
9998,9998,-0.5,4.503017,3.553944,2.784231,2.209573,1.794577,1.473266,1.210633,1.066785,...,12.588647,0.088099,0.015937,10.159751,0.107923,-0.000336,0.125740,9.887999,0.565968,1.074900
9999,9999,-1.0,0.900351,0.812242,0.873583,0.807319,0.775257,0.792305,0.776336,0.764657,...,6.566977,0.088099,0.653113,2.149050,0.828332,-0.000336,-0.000296,13.183827,0.654725,2.928964

In [36]:
x

,0,1,2,3,4,5,6,7,8,9,...,61,62,63,64,65,66,67,68,69,70
0,0.5,1.531688,1.366064,1.348957,1.179703,1.129366,1.031533,0.973250,0.963339,0.882490,...,21.325753,-0.000738,25.008361,-0.001391,24.594814,-0.000336,70.288663,-0.000531,-0.001955,-0.003699
1,-1.0,-0.243335,-0.241556,-0.184363,-0.236173,-0.241899,-0.219267,-0.265968,-0.294603,-0.343920,...,714.348788,-0.000738,1994.444211,3548.779977,4456.664085,5601.841811,5999.294212,-0.000532,1956.324177,-0.003699
2,0.5,-0.243335,-0.118572,-0.165968,-0.146762,-0.123755,-0.099449,-0.048321,-0.044985,-0.018212,...,-0.001150,-0.000738,-0.000723,-0.001391,-0.000887,-0.000336,-0.000296,-0.000532,-0.001956,-0.003698
3,-1.0,1.043054,0.928122,0.763915,0.780322,0.700080,0.645123,0.687316,0.693794,0.672837,...,34.395894,17.256368,0.002207,46.704813,74.523893,119.090616,219.146549,0.071375,82.378970,-0.003698
4,-0.5,4.505075,3.530311,2.778283,2.212718,1.815929,1.476635,1.217777,1.025065,0.949086,...,-0.001152,8.627815,0.005136,0.012634,0.047489,0.080026,109.573127,0.143282,41.188508,-0.003697
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,-0.5,0.875889,0.890131,0.978402,1.026985,1.053623,1.063049,1.020015,0.993813,0.916418,...,-0.001152,-0.000086,0.000303,1.850411,-0.000662,-0.000336,0.001258,0.000516,-0.001676,0.000478
9996,0.0,-0.122521,-0.206183,-0.128323,-0.201994,-0.159140,-0.178613,-0.222224,-0.223633,-0.285256,...,-0.001097,0.029309,-0.000717,-0.001372,-0.000827,-0.000234,-0.000089,3.296343,-0.001839,-0.003379
9997,-1.0,2.450257,2.113281,1.913165,1.677090,1.484911,1.326271,1.183276,1.034686,0.935451,...,18.610317,0.058704,0.007610,18.170452,16.020466,28.504445,22.861835,6.592171,30.301986,30.650275
9998,-0.5,4.503017,3.553944,2.784231,2.209573,1.794577,1.473266,1.210633,1.066785,0.935362,...,12.588647,0.088099,0.015937,10.159751,0.107923,-0.000336,0.125740,9.887999,0.565968,1.074900
9999,-1.0,0.900351,0.812242,0.873583,0.807319,0.775257,0.792305,0.776336,0.764657,0.739547,...,6.566977,0.088099,0.653113,2.149050,0.828332,-0.000336,-0.000296,13.183827,0.654725,2.928964

In [38]:
y1

        hhb
id
0      5.59
1      0.00
2     10.64
3      5.67
4     11.97
...     ...
9995  12.68
9996   8.46
9997   9.84
9998   6.38
9999   9.35

[10000 rows x 1 columns]

In [32]:
x

,0,1,2,3,4,5,6,7,8,9,...,61,62,63,64,65,66,67,68,69,70
0,0.5,1.531688,1.366064,1.348957,1.179703,1.129366,1.031533,0.973250,0.963339,0.882490,...,21.325753,-0.000738,25.008361,-0.001391,24.594814,-0.000336,70.288663,-0.000531,-0.001955,-0.003699
1,-1.0,-0.243335,-0.241556,-0.184363,-0.236173,-0.241899,-0.219267,-0.265968,-0.294603,-0.343920,...,714.348788,-0.000738,1994.444211,3548.779977,4456.664085,5601.841811,5999.294212,-0.000532,1956.324177,-0.003699
2,0.5,-0.243335,-0.118572,-0.165968,-0.146762,-0.123755,-0.099449,-0.048321,-0.044985,-0.018212,...,-0.001150,-0.000738,-0.000723,-0.001391,-0.000887,-0.000336,-0.000296,-0.000532,-0.001956,-0.003698
3,-1.0,1.043054,0.928122,0.763915,0.780322,0.700080,0.645123,0.687316,0.693794,0.672837,...,34.395894,17.256368,0.002207,46.704813,74.523893,119.090616,219.146549,0.071375,82.378970,-0.003698
4,-0.5,4.505075,3.530311,2.778283,2.212718,1.815929,1.476635,1.217777,1.025065,0.949086,...,-0.001152,8.627815,0.005136,0.012634,0.047489,0.080026,109.573127,0.143282,41.188508,-0.003697
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,-0.5,0.875889,0.890131,0.978402,1.026985,1.053623,1.063049,1.020015,0.993813,0.916418,...,-0.001152,-0.000086,0.000303,1.850411,-0.000662,-0.000336,0.001258,0.000516,-0.001676,0.000478
9996,0.0,-0.122521,-0.206183,-0.128323,-0.201994,-0.159140,-0.178613,-0.222224,-0.223633,-0.285256,...,-0.001097,0.029309,-0.000717,-0.001372,-0.000827,-0.000234,-0.000089,3.296343,-0.001839,-0.003379
9997,-1.0,2.450257,2.113281,1.913165,1.677090,1.484911,1.326271,1.183276,1.034686,0.935451,...,18.610317,0.058704,0.007610,18.170452,16.020466,28.504445,22.861835,6.592171,30.301986,30.650275
9998,-0.5,4.503017,3.553944,2.784231,2.209573,1.794577,1.473266,1.210633,1.066785,0.935362,...,12.588647,0.088099,0.015937,10.159751,0.107923,-0.000336,0.125740,9.887999,0.565968,1.074900
9999,-1.0,0.900351,0.812242,0.873583,0.807319,0.775257,0.792305,0.776336,0.764657,0.739547,...,6.566977,0.088099,0.653113,2.149050,0.828332,-0.000336,-0.000296,13.183827,0.654725,2.928964

In [28]:
pd.merge(x,y1,how='left',on='id')

KeyError: 'id'

In [19]:
x_train, x_test, y_train, y_test = train_test_split(x,y1, test_size=0.2, random_state=43)

model = XGBRegressor(n_jobs=1)
model.fit(x_train,y_train)
y_pred = model.predict(x_test)
mae = mean_absolute_error(y_pred, y_test)
print('xgboost mae 는', mae)

x_train, x_test, y_train, y_test = train_test_split(x,y2, test_size=0.2, random_state=43)
model = XGBRegressor(n_jobs=1)
model.fit(x_train,y_train)
y_pred = model.predict(x_test) 
mae = mean_absolute_error(y_pred, y_test)
print('xgboost mae 는', mae)

x_train, x_test, y_train, y_test = train_test_split(x,y3, test_size=0.2, random_state=43)
model = XGBRegressor(n_jobs=1)
model.fit(x_train,y_train)
y_pred = model.predict(x_test)
mae = mean_absolute_error(y_pred, y_test)
print('xgboost mae 는', mae)

x_train, x_test, y_train, y_test = train_test_split(x,y4, test_size=0.2, random_state=43)
model = XGBRegressor(n_jobs=1)
model.fit(x_train,y_train)
y_pred = model.predict(x_test)
mae = mean_absolute_error(y_pred, y_test)
print('xgboost mae 는', mae)

xgboost mae 는 1.2829265556406977
xgboost mae 는 0.7349076338338851
xgboost mae 는 2.2790482931423184
xgboost mae 는 1.4711147229343653

In [88]:
model2 = joblib.load('./model_save/mae78.17250055599212.dat')

# 제출

In [42]:
# 제출
pred = model1.predict(x_predict)

pred = model1.predict(x_predict)
submission = pd.read_csv('sample_submission.csv', index_col=0)
submission['hhb'] = pred[:,0]
submission['hbo2'] = pred[:,1]
submission['ca'] = pred[:,2]
submission['na'] = pred[:,3]

submission.to_csv('submission0611_1.csv')

pred = model1.predict(x_predict1)
submission['hhb'] = pred[:,0]
submission['hbo2'] = pred[:,1]
submission['ca'] = pred[:,2]
submission['na'] = pred[:,3]
submission.to_csv('submission1_1.csv')

In [255]:
submission

          hhb   hbo2      ca     na
id
10000   7.330  3.861   7.608  2.890
10001   6.530  3.993   6.310  2.105
10002  11.439  4.057   9.335  3.524
10003   8.239  4.599   9.715  3.084
10004   8.279  3.615   9.837  4.130
...       ...    ...     ...    ...
19995   6.134  4.480   9.480  3.342
19996   7.258  4.027   9.550  3.275
19997   9.724  3.333   9.786  3.206
19998   9.455  4.714  11.051  2.773
19999   6.110  4.011   9.873  3.264

[10000 rows x 4 columns]